context:
  name: polars-xdt
  version: "0.17.0"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ name | replace("-", "_") }}-${{ version }}.tar.gz
  sha256: a8fa359443421dbd6e8375c1cfc12732066ecf41fa1ddedd241b3c129e38afab

build:
  script:
    - python -m pip install . -vv
    - cargo-bundle-licenses --format yaml --output ./THIRDPARTY.yml
  number: 0

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ compiler('rust') }}
    - ${{ stdlib('c') }}
    - cargo-bundle-licenses
    - if: build_platform != target_platform
      then:
        - python
        - cross-python_${{ target_platform }}
        - maturin >=1,<2
  host:
    - python
    - pip
    - maturin >=1,<2
    # https://github.com/pola-rs/polars-xdt/blob/fe4c8e7228bd25a32083e214a364943bcb42cd93/pyproject.toml#L2
    - polars >=1.5.0
  run:
    - python
    - polars >=1.5.0
    - if: match(python, "<3.10")
      then:
        - typing-extensions

tests:
  - python:
      imports:
        - polars_xdt
      pip_check: true

about:
  homepage: https://github.com/pola-rs/polars-xdt
  summary: Polars plugin offering eXtra stuff for DateTimes
  # MIT from polars-xdt, BSD-3-Clause from pandas and numpy
  license: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml
    - licenses/NUMPY_LICENSE.txt
    - licenses/PANDAS_LICENSE.txt
  # https://github.com/pola-rs/polars-xdt/issues/92
  documentation: https://marcogorelli.github.io/polars-xdt-docs
  repository: https://github.com/pola-rs/polars-xdt

extra:
  recipe-maintainers:
    - pavelzw
